### ISSUE TITLE
안녕하세요?

### ISSUE THREAD

**Issue by unoske251** [pronist/upbit-trading-bot#1]
혹시 어떻게 사용하는지 알수있을까요...?

**Comment by pronist** [comment]
@unoske251 사용법은 README 문서에 있긴한데.. 정확히 어떤 점이 궁금하신가요?

**Comment by unoske251** [comment]
아 이런게 처음이라서...아예 실행방법을 모르겠네요 ㅎㅎㅎ...
원격으로라도 해주실수있으신가요~?

**Comment by pronist** [comment]
@unoske251 그 부분은 어려울 수도 있다는 점 양해부탁드립니다. 해당 프로그램은 일반적인 사용자를 위한 것이라기보다는 개발자들을 위한 것입니다. 소스코드를 받고 전략을 소스코드로 구상하셔야 합니다.  또한 전략 구성을 위한 **go** 언어를 알고있지 않다면 해당 프로젝트는 사용하기 어려우시다는 점 참고부탁드립니다.
